-- AlterTable
ALTER TABLE `WalkAround` ADD COLUMN `fl` INTEGER NULL,
    ADD COLUMN `fr` INTEGER NULL,
    ADD COLUMN `rl` INTEGER NULL,
    ADD COLUMN `rl2` INTEGER NULL,
    ADD COLUMN `rr` INTEGER NULL,
    ADD COLUMN `rr2` INTEGER NULL,
    ADD COLUMN `size` VARCHAR(191) NULL,
    ADD COLUMN `tireBrand` VARCHAR(191) NULL,
    ADD COLUMN `tirePartNumber` VARCHAR(191) NULL;
