-- AlterTable
ALTER TABLE `WalkAround` ADD COLUMN `brand` VARCHAR(191) NULL,
    ADD COLUMN `eCCA` INTEGER NULL,
    ADD COLUMN `eRatedCCA` INTEGER NULL,
    ADD COLUMN `eRatedVoltage` INTEGER NULL,
    ADD COLUMN `eVoltage` INTEGER NULL,
    ADD COLUMN `nCCA` INTEGER NULL,
    ADD COLUMN `nVoltage` INTEGER NULL,
    ADD COLUMN `partNumber` VARCHAR(191) NULL;
