import type { Metadata } from "next";
import SessionProvider from "../../components/SessionProvider";
import { getServerSession } from "next-auth";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <SessionProvider session={session}>
      <main className="mx-auto max-w-5xl text-2xl flex gap-2">{children}</main>
    </SessionProvider>
  );
}
